-- ============================================================
-- رصد — تهيئة مشروع Supabase جديد (مرة واحدة)
-- نفّذ في: Supabase Dashboard → SQL Editor → Run
-- ============================================================

-- 1) الجداول الأساسية
CREATE TABLE IF NOT EXISTS public.grade_system_state (
  id text PRIMARY KEY,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'teacher'
    CHECK (role IN ('superadmin','stageadmin','monitor','teacher')),
  full_name text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  stage_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  teacher_id text,
  sections jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT profiles_stage_ids_array CHECK (jsonb_typeof(stage_ids) = 'array')
);

CREATE TABLE IF NOT EXISTS public.audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  actor_name text NOT NULL DEFAULT '',
  actor_role text NOT NULL DEFAULT '',
  stage_id text,
  stage_name text,
  action text NOT NULL DEFAULT '',
  details text NOT NULL DEFAULT '',
  level text NOT NULL DEFAULT 'info',
  app_version text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_audit_events_created_at ON public.audit_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles (role);

ALTER TABLE public.grade_system_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;

-- 2) دوال الصلاحيات
CREATE OR REPLACE FUNCTION public.is_superadmin()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.is_active IS DISTINCT FROM false
      AND p.role = 'superadmin'
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin_role()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.is_active IS DISTINCT FROM false
      AND p.role IN ('superadmin','stageadmin','monitor')
  );
$$;

CREATE OR REPLACE FUNCTION public.can_access_stage_row(row_id text)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.is_superadmin()
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_active IS DISTINCT FROM false
        AND p.stage_ids ? replace(row_id, 'stage_', '')
    );
$$;

-- 3) سياسات profiles
DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own" ON public.profiles
  FOR SELECT TO authenticated
  USING (id = auth.uid() OR public.is_superadmin());

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE TO authenticated
  USING (id = auth.uid() OR public.is_superadmin())
  WITH CHECK (id = auth.uid() OR public.is_superadmin());

-- 4) سياسات grade_system_state (مبسّطة للتشغيل الأولي)
DROP POLICY IF EXISTS "state_deny_anon" ON public.grade_system_state;
CREATE POLICY "state_deny_anon" ON public.grade_system_state
  FOR ALL TO anon USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "state_select_auth" ON public.grade_system_state;
CREATE POLICY "state_select_auth" ON public.grade_system_state
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "state_insert_auth" ON public.grade_system_state;
CREATE POLICY "state_insert_auth" ON public.grade_system_state
  FOR INSERT TO authenticated WITH CHECK (public.is_admin_role());

DROP POLICY IF EXISTS "state_update_auth" ON public.grade_system_state;
CREATE POLICY "state_update_auth" ON public.grade_system_state
  FOR UPDATE TO authenticated
  USING (public.is_admin_role())
  WITH CHECK (public.is_admin_role());

DROP POLICY IF EXISTS "state_delete_auth" ON public.grade_system_state;
CREATE POLICY "state_delete_auth" ON public.grade_system_state
  FOR DELETE TO authenticated USING (public.is_admin_role());

-- 5) سياسات audit
DROP POLICY IF EXISTS "audit_events_insert_auth" ON public.audit_events;
CREATE POLICY "audit_events_insert_auth" ON public.audit_events
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "audit_events_select_admin" ON public.audit_events;
CREATE POLICY "audit_events_select_admin" ON public.audit_events
  FOR SELECT TO authenticated USING (public.is_admin_role());

-- ============================================================
-- 6) بعد إنشاء مستخدم Auth من الواجهة، اربط ملف رئيس الكنترول:
--    Authentication → Users → انسخ User UID
--    ثم نفّذ (استبدل USER_UUID_HERE):
-- ============================================================
-- INSERT INTO public.profiles (id, role, full_name, email, stage_ids, is_active)
-- VALUES (
--   'USER_UUID_HERE'::uuid,
--   'superadmin',
--   'رئيس الكنترول',
--   'a.shafaie@hotmail.com',
--   '[]'::jsonb,
--   true
-- )
-- ON CONFLICT (id) DO UPDATE SET
--   role = EXCLUDED.role,
--   email = EXCLUDED.email,
--   is_active = true,
--   updated_at = now();
